### ISSUE TITLE
On the Sample app, ThunderboltIocSamples.WpfCore error

### ISSUE THREAD

**Issue by MickCG** [AlyElHaddad/ThunderboltIoc#2]
Here is what I did. Thought I would clone again the ThunderboltIoc repository. I wanted to check it against my Xamarin test. I fired up the Wpf solution with VS 2022. I then checked for Nuget updates and installed the ThunderboltIoc 1.2.1 package. I compiled and there were no errors. Next I fired it up and at the following in ThunderboltResolveExtension class:

public override object ProvideValue(IServiceProvider serviceProvider)
        {
            return Type is null ? null : ThunderboltActivator.Container.GetService(Type);
        }
The following error:
System.InvalidOperationException
  Message=Unable to locate a registered implementation for a service of type 'MyThunder.ViewModels.MainViewModel'.

I want to emphasis I made zero changes to the code before compiling and running the example.

**Comment by AlyElhaddad** [comment]
@MickCG thank you for pointing this out. The bug was related to a source generator issue ([the relevant discussion on rosyln repo](https://github.com/dotnet/roslyn/discussions/47517)).

It has been resolved now. Please try version 1.2.2 and let me know whether or not you can reproduce the problem.

**Comment by MickCG** [comment]
Updated the Nuget package to the 1.2.2 and am still getting the same error.

**Comment by AlyElhaddad** [comment]
I will close this because as per [your comment on the other issue](https://github.com/AlyElHaddad/ThunderboltIoc/issues/1#issuecomment-1014015652), the WPF problem has been resolved in version `1.2.3`.
